### ISSUE TITLE
Change box colors to UB-ERI colors (CSS)

### ISSUE THREAD

**Issue by sharp-lilac** [sharp-lilac/shiny-tamr-app-uberi#30]
UB-ERI colors may be found on the website https://www.uberibz.org/
purple, blue, orange, and green

Change the CSS box style to match these, and adjust text color as needed so text is legible

box styles in custom_style.css are in section /* Custom styles for boxes */

**Comment by Konkaseeti** [comment]
Ill work on this one.

**Comment by Konkaseeti** [comment]
Should I replace the existing section-box and their alternate or create new ones with the UB-ERI color set ?

**Comment by sharp-lilac** [comment]
Good question. You can replace the box styling. We can always access the old ones by 'checking out' a previous state of the repository if needed. Code is never lost in git, which is really nice. This way we can keep the code short(ish) without truly losing anything.
