### ISSUE TITLE
Add locality descriptions to map page

### ISSUE THREAD

**Issue by sharp-lilac** [sharp-lilac/shiny-tamr-app-uberi#53]
On the map page, add to the right side of the map a table (DT::dataTableOutput in ui, and DT::renderDataTable in server) of locality descriptions with caption:

Table of reef localities surveyed by reef zones, years, and survey types, for each Turneffe Atoll Marine Reserve locality, with a description where available. Last updated Feb 2024.

| Locality               | Reef Zones Surveyed | Description of Characteristics                                                           | Benthic Survey Years              | Coral Survey Years              | Fish Survey Years                        |
|------------------------|---------------------|------------------------------------------------------------------------------------------|-----------------------------------|---------------------------------|------------------------------------------|
| 1062                   | BR, DFR, SFR       | Primarily flat substrate with reef structure spread throughout. Large patches of coral colony. | 2010-2018, 2021, 2023            | 2010-2018, 2021                 | 2010-2015, 2017, 2018, 2021, 2023       |
| 1071                   | DFR, SFR           |                                                                                          | 2012-2018                         | 2012-2018                       | 2012-2015, 2017, 2018                   |
| 1206                   | BR, DFR, SFR       | Large reef structure, with significant rugosity.                                         | 2010-2018, 2021, 2023            | 2010-2018, 2021                 | 2010-2015, 2017, 2018, 2021, 2023       |
| 2226                   | SFR                |                                                                                          | 2012-2013                         | 2012-2013                       | NA                                       |
| Caye Bokel (CB)        | BR, DFR, SFR       |                                                                                          | 2010-2018, 2021, 2023            | 2010-2018, 2021                 | 2010-2015, 2017, 2018, 2021, 2023       |
| Cockroach Zone 2 (CZ2) | DFR, SFR           | Large spur and groove reef structure.                                                    | 2014-2018, 2021, 2023            | 2014-2018, 2021                 | 2015, 2017, 2018, 2021, 2023            |
| Mauger Point (MP)      | BR, DFR, SFR       |                                                                                          | 2013-2018, 2021, 2023            | 2013-2018, 2021                 | 2013-2015, 2017, 2018, 2021, 2023       |
| Soldier Point (SP)     | BR, DFR, SFR       |                                                                                          | 2013-2018, 2021, 2023            | 2013-2018                       | 2013-2015, 2017, 2018, 2021, 2023       |
| West Point 4 (WP4)     | BR, DFR, SFR       | The survey area is on a slope, with reef structures located on large areas of sand.      | 2010-2018, 2021, 2023            | 2010-2018, 2021                 | 2010-2015, 2017, 2018, 2021, 2023       |
| West Point 5 (WP5)     | BR, DFR, SFR       | The survey area is on a slope, with reef structures located on large areas of sand.      | 2010-2012, 2014-2018, 2021, 2023 | 2010-2018, 2021                 | 2010-2015, 2021, 2023                   |
| West Point 6 (WP6)     | BR, DFR, SFR       |                                                                                          | 2010-2012                         | 2010-2012                       | NA                                       |

**Comment by sharp-lilac** [comment]
@Konkaseeti At some point, I think this would be a great one for you to try! It is good to learn how to create clean, interactable tables in shiny. My recommendation would be to try DT::dataTableOutput (ui) and DT::renderDataTable (server). You can see an example already in the code from adding the coral codes table underneath the coral cover by species plot

**Comment by Konkaseeti** [comment]
Does this require a new csv file to be made with that data ?

**Comment by sharp-lilac** [comment]
Yes, that would be a good approach. You can add it to a new folder data/other/

**Comment by Konkaseeti** [comment]
I actually removed the interactible parts. The table feels too big to put beside the map even if I changed it to show less rows at a time. Mayhaps it should go on the bottom of the page instead?
