### ISSUE TITLE
Color the nav tabs orange

### ISSUE THREAD

**Issue by sharp-lilac** [sharp-lilac/shiny-tamr-app-uberi#78]
The navigation tabs (nav tabs) should be colored orange (#f1d1c1). These tabs may be found on the Coral Health Explorer, Coral Cover Explorer, and Fish Observations Explorer.

![image](https://github.com/user-attachments/assets/a9edec2a-ba88-429f-94c7-364ae1190b9a)

**Comment by Konkaseeti** [comment]
Do you want the active one to be orange or make both of them orange ?

**Comment by sharp-lilac** [comment]
Both of them orange with black text and border, please! Thanks
