### ISSUE TITLE
Add key data summary boxes to home page

### ISSUE THREAD

**Issue by sharp-lilac** [sharp-lilac/shiny-tamr-app-uberi#8]
Add output boxes at top of home page, drawing attention. Highlighting summary data:
Total number of unique data collectors
Total number of unique years
Total number of unique localities

And/or more interesting summary values that would be engaging to see...

Key Point: If the data changes (e.g., new dataset in 2025 comes in), the key data summary boxes should change

**Comment by sharp-lilac** [comment]
@Konkaseeti 

If you want something more challenging to try, this might be a fun one for you! You would have to find some data values from the datasets, and define those values in data_prepare.R. 

For example, could be started like this at the bottom of data_prepare.R:
```
# Prepare key vectors ---------------------------
# Count number of unique data collectors across the 3 master dataframes
number_collectors <- length(unique(c(df_master_benthic$Collector, df_master_fish$Collector, df_master_coral$Collector)))
```

Then you would display the values you calculate at the top of the home page using a `valueBoxOutput()` on the ui, and a corresponding `renderValueBox({})` on the server side. Here is some guidance: https://www.rdocumentation.org/packages/shinydashboard/versions/0.7.2/topics/renderValueBox

**Comment by Konkaseeti** [comment]
I'll give it a go.
