### ISSUE TITLE
Add logo of UB-ERI to the home page

### ISSUE THREAD

**Issue by sharp-lilac** [sharp-lilac/shiny-tamr-app-uberi#9]
Create ui and server code which will display the ub-eri logo on home page from the images folder

**Comment by sharp-lilac** [comment]
UBERI_Logo.png in www/images

**Comment by sharp-lilac** [comment]
Top right corner?

**Comment by Konkaseeti** [comment]
I placed the logo on the top right and bottom left, to choose from. 

Bottom feels better.
Top left looks better, Should it be bigger ? when i size it up it makes that header bar bigger as well.

![top](https://github.com/user-attachments/assets/98929369-fea7-4e9b-bd45-d1895b2d7a72)
![bottom](https://github.com/user-attachments/assets/2814f087-2d46-41e5-a4be-e5a4698bb16b)

**Comment by sharp-lilac** [comment]
@Konkaseeti I think let's stick with top right! Thanks for checking both
